//
//  StudentLocationModel.swift
//  OnTheMap
//
//  Created by Jean-Marc Kampol Mieville on 12/30/2559 BE.
//  Copyright © 2559 Jean-Marc Kampol Mieville. All rights reserved.
//

import Foundation

// StudentInformation
struct StudentLocationModel {
    
    // Student Location Model information
    static let objectIdKey = "objectId"
    static let uniqueKey = "uniqueKey"
    static let firstNameKey = "firstName"
    static let lastNameKey = "lastName"
    static let mapStringKey = "mapString"
    static let mediaURLKey = "mediaURL"
    static let latitudeKey = "latitude"
    static let longitudeKey = "longitude"
    static let createdAtKey = "createdAt"
    static let updatedAtKey = "updatedAt"
    
    // ACL not needed
    //static let ACLKey = "ACL"
    
    static var student = [StudentModel]()
    
    // Getting list of Student
    static func getStudentList(_ newStudents: [[String: Any]]) {
        student.removeAll()
        
        // Looping in students
        for eachStudent in newStudents {
            
            guard let newStudent = StudentModel(student: eachStudent) else {
                return
            }
            
            //let newStudent = StudentModel(student: eachStudent)
            
            // Append student in students to the list
            StudentLocationModel.student.append(newStudent)
        }
    }
    
}

// For reference from Udacity.com
/*
 Key: objectId
 Description: an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
 Parse Type: String
 Example Value: 8ZExGR5uX8
 Key: uniqueKey
 Description: an extra (optional) key used to uniquely identify a StudentLocation; you should populate this value using your Udacity account id
 Parse Type: String
 Example Value: 1234
 Key: firstName
 Description: the first name of the student which matches their Udacity profile first name
 Parse Type: String
 Example Value: John
 Key: lastName
 Description: the last name of the student which matches their Udacity profile last name
 Parse Type: String
 Example Value: Doe
 Key: mapString
 Description: the location string used for geocoding the student location
 Parse Type: String
 Example Value: Mountain View, CA
 Key: mediaURL
 Description: the URL provided by the student
 Parse Type: String
 Example Value: https://udacity.com
 Key: latitude
 Description: the latitude of the student location (ranges from -90 to 90)
 Parse Type: Number
 Example Value: 37.386052
 Key: longitude
 Description: the longitude of the student location (ranges from -180 to 180)
 Parse Type: Number
 Example Value: -122.083851
 Key: createdAt
 Description: the date when the student location was created
 Parse Type: Date
 Example Value: Feb 25, 2015, 01:10
 Key: updatedAt
 Description: the date when the student location was last updated
 Parse Type: Date
 Example Value: Mar 09, 2015, 23:34
 Key: ACL
 Description: the Parse access and control list (ACL), i.e. permissions, for this StudentLocation entry
 Parse Type: ACL
 Example Value: Public Read and Write
 
 */
